title: Prashant Das, PhD
url: ReadMe.md
  
logo: "/images/profile3.png?raw=true"  # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a research engineer with 10+ years of experience
  in a broad range of topics related to fluid dynamics. <br>

  <a href="https://www.linkedin.com/in/prashdas/">View My LinkedIn Profile</a> 
  <br><br>
  <br><br>
layout: full

theme: jekyll-theme-minimal
