theme: jekyll-theme-minimal
title: Prashant Das, PhD
logo: "/images/profile.png?raw=true" # your photo (or logo) here

description: I am a research engineer with 10+ years of experience in a broad range of topics in experimental and computational fluid dynamics relevant to mechanical and biomedical engineering systems.
