theme: jekyll-theme-minimal
title: Prashant Das, PhD


description: I am a research engineer with 10+ years of experience in a broad range of topics in experimental and computational fluid dynamics relevant to mechanical and biomedical engineering systems.
