title: Prashant Das, PhD
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a research engineer with 10+ years of experience
  in a broad range of topics in experimental and computational
  fluid dynamics relevant to mechanical and biomedical engineering systems.
<br><br>
  <a href="https://www.linkedin.com/in/prashdas/">View My LinkedIn Profile</a> 
  <br><br>
  <br><br>
theme: jekyll-theme-minimal
